# -*- coding: utf-8 -*-
"""HousePricePrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpyvfumLGEmtCdeS1hq1IMcIRs5WRRpn

#Imports
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import warnings
import seaborn as sns
import os
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
warnings.filterwarnings('ignore')

"""# Data Extraction"""

import kagglehub
path = kagglehub.dataset_download("ericmauricio/home-data-for-ml-course")

os.listdir(path)

df=pd.read_csv(os.path.join(path,"train.csv"))
df.drop('Id',axis=1,inplace=True)

df.describe()

df.info()

df.shape

"""# Visusalisation"""

cols=df.columns

fig, axes = plt.subplots(nrows=1, ncols=30, figsize=(120, 3))  # width 30 inches
for i in range(30):
    sns.scatterplot(x=df[cols[i]], y=df['SalePrice'], ax=axes[i])
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(nrows=1, ncols=49, figsize=(176, 3))  # width 30 inches
for i in range(30,79):
    sns.scatterplot(x=df[cols[i]], y=df['SalePrice'], ax=axes[i-30])
plt.tight_layout()
plt.show()

"""# Preprocessing"""

#imputing missin with feature mean
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
df['LotFrontage']=imputer.fit_transform(df['LotFrontage'].values.reshape(-1,1))

drop_features_cols=['MiscFeature','PoolQC','FireplaceQu','MasVnrType','Alley','Fence']

def drop_features(drop_features,df):
  for feature in drop_features:
    df.drop(feature,axis=1,inplace=True)
  return df

df=drop_features(drop_features_cols,df)

#Dropping the entire row which has null values.
df=df.dropna(axis=0,inplace=False)

#extracting categorical and numerical columns
categorical_cols=df.select_dtypes(include='object').columns
numerical_cols=df.select_dtypes(exclude='object').columns
numerical_cols=numerical_cols[:-1]

df[categorical_cols].isnull().sum()

df[categorical_cols].isnull().sum()

#encoding categorical data
encoder = OneHotEncoder()

def encode_categorical(df,encoder):
  categorical_encoded=pd.DataFrame(encoder.fit_transform(df[categorical_cols]).toarray(),columns=encoder.get_feature_names_out())
  return categorical_encoded

target=df['SalePrice']
df.drop('SalePrice',axis=1,inplace=True)

categorical_encoded_df=encode_categorical(df,encoder)

#Standardization of numerical data.
scaler=StandardScaler()
numerical_scaled_df=pd.DataFrame(scaler.fit_transform(df[numerical_cols]),columns=numerical_cols)

#combine the numerical_df and categorical_encoded_df
X=pd.concat([numerical_scaled_df,categorical_encoded_df],axis=1)

#splitting the dataset
y=target
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

x_train.shape

y_train.shape

"""# Training"""

from sklearn.ensemble import RandomForestRegressor
Random_model = RandomForestRegressor(
    n_estimators=500,
    max_depth=12,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features="sqrt",
    random_state=42
)

"""# Evaluation"""

def evalualte_model(model,x_train,x_test,y_train,y_test):
  print(f"Model: {model}")
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test)

  mae = mean_absolute_error(y_test, y_pred)
  mse = mean_squared_error(y_test, y_pred)
  rmse = np.sqrt(mse)
  r2 = r2_score(y_test, y_pred)

  print("MAE:", mae)
  print("MSE:", mse)
  print("RMSE:", rmse)
  print("R2:", r2)

evalualte_model(Random_model,x_train,x_test,y_train,y_test)

y_pred=Random_model.predict(x_test)
submission=pd.DataFrame({'Id':df.index,'SalePrice':y_pred})

